/**
 * Machine-readable outcome of any HTTP exchange.
 * Never duplicated with a resource `status` field.
 */
export enum ResponseMessage {
  SUCCESS = 'SUCCESS',
  CREATED = 'CREATED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WALLET_FROZEN = 'WALLET_FROZEN',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  UPSTREAM_UNAVAILABLE = 'UPSTREAM_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
